version: "3.0"
services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Bookfair@2025#"
      MYSQL_DATABASE: bookfair_db
      MYSQL_USER: bookfair
      MYSQL_PASSWORD: "Bookfair@2025#"
    ports:
      - "8042:3306"  
    volumes:
      - db_data:/var/lib/mysql

  # PhpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_db
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8043:80"

  # NestJS Backend
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - "8041:3000"  
    depends_on:
      - db  
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: bookfair
      DB_PASSWORD: "Bookfair@2025#"
      DB_DATABASE: bookfair_db
    command: ["npm", "run", "start:dev"]

volumes:
  db_data: